name: Build + test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-windows:
    name: Build+Test Windows
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        override: true
        profile: minimal
        toolchain: stable
        components: clippy
    - name: Build
      run: cargo build --verbose && cargo test --verbose
